### ISSUE TITLE
SVG not fully rendered on iOS with latest versions

### ISSUE THREAD

**Issue by StefanWallin** [software-mansion/react-native-svg#2422]
### Description

Rendering in `"react-native-svg": "15.6.0"`
<img width="1035" alt="iOS and Android sim/emu showing SVG rendering" src="https://github.com/user-attachments/assets/b28bfc4b-0f6c-41f0-afc3-0502619c7360">

I made this SVG in Figma recently and tried using it in my app. I was on `react-native-svg@15.3.0` at the time. So I tried upgrading yesterday to 15.5.0 and to my surprise it worked on android but not iOS, so something was fixed in 15.3.0...15.5.0 that caused the SVG in the snack to start working on Android. It does still not work in iOS. It works on web. The issue is that the bottom right QR-icon is not rendered as shown on the attached image. The right hand render of the image is the expected state, the left hand shows how it renders previously on android.

I tried today before submitting this bug with version 15.6.0 and as you can see in the top screenshot it is still buggy.

### Steps to reproduce

1. Use `./components/Icon.jsx` from https://snack.expo.dev/@stefanwallin/react-native-svg-not-rendering-fully-on-ios with `react-native-svg@15.2.0` as in the snack.
2. STATUS: iOS :x: & Android :x: is not rendering the bottom QR-icon. 
3. Update `react-native-svg@15.6.0` (expo go does not support `> 15.2.0` yet)
4. STATUS: iOS :x: is not rendering the bottom QR-icon, but Android ✅ WORKS

### Snack or a link to a repository

https://snack.expo.dev/@stefanwallin/react-native-svg-not-rendering-fully-on-ios

### SVG version

15.6.0

### React Native version

0.74.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

iPhone 13 mini

### Acknowledgements

Yes

**Comment by djaffer** [comment]
same issue. Even for web it does this.

**Comment by StefanWallin** [comment]
> same issue. Even for web it does this.

Haven't tested explicitly with web, but 15.2.0 (in the snack) works on the snack web preview (Brave, Version 1.68.141 Chromium: 127.0.6533.120 (Official Build) (arm64))

**Comment by djaffer** [comment]
If you switch page from 1 to another using routes. It breaks.

**Comment by facuacostag** [comment]
I've seen the same issue. SVGs work fine on iOS in version `15.0.2` and `15.0.3` but when updating to `15.0.4` or bigger they stop rendering some of the parts.

**Comment by bohdanprog** [comment]
Hello @facuacostag, @djaffer.
Can you provide any examples?

**Comment by bohdanprog** [comment]
@StefanWallin I'm not sure about the problem because when I changed that line: `<G mask="url(#a)">` `<G>`

here is the full example:
```tsx
const Icon = () => {
  const width = 200;
  const height = 200;
  const color = 'black';
  return (
    <Svg width={width} height={height} viewBox="0 0 475 599" fill="none">
      <G clipPath="url(#a)">
        <Mask
          id="a"
          width={147}
          height={147}
          x={391}
          y={333}
          maskUnits="userSpaceOnUse"
          style={{
            maskType: 'luminance',
          }}>
          <Path fill="#fff" d="M538 333H391v147h147V333z" />
        </Mask>
        <G mask="url(#a)">
          <Path
            fill={color}
            d="M458.4 382h-6.1v-12.3h6v6.2h12.3v6.1h-6.1v6.1h-6.1V382zm12.2 73.5v-6.1h-6.1v6.1h6.1zm-6.1-91.9v-6.1h-12.3v6.1h6.2v6.1h6.1v-6zm49-6.1v36.8h-6.1V388h-24.5v-30.6h30.6zm-6.1 24.5v-18.4H489V382h18.4zm-85.8 12.3h-6.1v6h12.3v-6h-6.2zm0 18.3h6.1v6.1h6.2v-18.3h-6.1v6.1h-12.3v12.3h6.1v-6.2zm30.6 6.1V431h6.2v-12.3h-6.1zm24.6-61.2h-6.2v18.4h6.1v-18.4zm0 30.6V382h-6.2v6.1h6.1zM495 376h6.1v-6.1h-6v6zm-61.2-6.1h-6.1v6h6v-6zm12.2-12.3v30.6h-30.6v-30.6H446zm-6.1 6.1h-18.4V382H440v-18.4zm55.1 30.6v6.2h-6v-6.1h-12.3v6h-6v-6h-18.4V388H446v6.1h-6v6.2h6.1v12.2h6.1v-6.1h6.2v12.3h6.1v-12.3h18.4v6.1h-12.3v6.1H483v6.2h6.1v-18.4h6.1v6.1h6.1V425h6.2v-6.1h6.1v-6.2h-6.1v-6.1h-6.1v-6.1h6v-6.1h-12.2zm-67.4 49h6.2v-6h-6.1v6zm-12-18.3h30.6v30.6h-30.6V425zm6.1 24.5H440V431h-18.4v18.4zm73.5-18.4V425H489v6.1h6.1zm0 6.1H489v6.1h-6.1v-6h-6.1V431h6v-6.1h-12.2v-6.1h-6.1V431h-6.1v6.1h-6.1v18.4h6v-6.1h6.2v-6.1h12.3v12.2h6v-6.1h6.2v6.1h12.3v-6.1h6v-6.1h-12.2V437zM440 418.7h6.1v-6H440v6zm61.3 12.3v6.1h6v6.1h6.2V425h-6.1v6.1h-6.1zm12.2 24.5v-6.1h-6.1v6.1h6.1zm0-49v-6.1h-6.1v6.1h6.1zm-12.3-61.3h24.6v24.6H538V333h-36.8v12.3zm-98 24.6v-24.6h24.6V333H391v36.8h12.3zm24.6 98h-24.6v-24.6H391V480h36.8v-12.3zm98-24.6v24.6h-24.5V480H538v-36.8h-12.3z"
          />
        </G>
      </G>
      <Path
        fill={color}
        fillRule="evenodd"
        d="M247.3 22.2A52 52 0 01284 43a51 51 0 018.5 39.7c-10.1 46.6-19.2 87-27.8 125.5A7273 7273 0 00214.4 445v.2c-5 50.8.1 80.3 11 97.5a46.6 46.6 0 0014.6 14.7c-73.8-8.2-107.5-11.1-151.8-15L58.5 540C16.4 536.3 11 470.5 11 447c0-179 0-180.5 3.5-376 .3-16 21.1-49 44-49h181c2.6 0 5.2 0 7.8.2zm20.6.9c16.8 1.4 30.2 4.8 35.6 13.9 8.2 13.9 6.5 34 6.5 34h43c5.7 0 14.5 12.8 14 18.5-12.3 126.7-15.7 179.6-19 230.8-2.3 36.5-4.6 72.2-10 133.2-4.3 48-20.5 107.5-66.5 107.5l-13.3-1.5a43.6 43.6 0 01-28.5-19.4c-10-15.7-15.3-43.7-10.3-94.2 17.7-92 33-160.2 50.1-236.5 8.7-38.4 17.7-79 27.8-125.6a56 56 0 00-9.2-43.7 53.7 53.7 0 00-20.2-17zm46.3 447.6c-4 30.9-22.1 54-40.5 51.7-18.3-2.4-30-29.4-26-60.4s22.2-54 40.6-51.7c18.3 2.4 30 29.4 26 60.4zM69 176c-19.9-1-35.8 15.7-36.5 35.5C29 312 29 320.5 29 375c0 17.8 10.8 31.1 28.5 32.5 43.7 3.6 73.5 5.6 106 7.7l12 .8c16.2 1.1 29.2-10.5 32-26.5l3.3-18.6c11.6-66.5 14.1-81 24.7-151.4 2.7-18-5.8-40-24-40-75 0-75.5 0-142.5-3.5zm234 52.3h-3.6V221h3.5v3.6h7.2v3.6h-3.6v3.5h-3.6v-3.6zm7 0h3.6v3.5h-3.5v-3.6zm0-3.6V214h3.6v10.7h-3.5zm-3.5-3.6h-3.6v-3.5h-3.5V214h7.1v7.1zm3.6 49.9v-3.6h-3.6V264h7.1v7.1h3.6v-3.6h3.6v3.6h7v-3.6h3.6v3.6h3.6v-3.6h-3.6V264h3.6v-10.7h-3.6v-3.6h3.6v-3.5h-3.6v-3.6h3.6V239h-3.6v-3.5h3.6V214h-17.8v17.8h14.2v3.6h-7v3.5h-3.6v-3.5h-7.2v3.5h-3.5v-3.5h-10.7v-3.6h-3.6V214H278v17.8h17.8v3.6h-3.6v3.5h3.6v7.2h-3.6v3.5h3.6v-3.5h3.6v-3.6h3.5v7.1h-3.5v7.2h3.5v3.5h-3.5V271h3.5v-3.6h3.6v3.6h3.6zm-3.6-21.4v7.2h-3.6v-7.2h3.6zm3.6 0v-3.5h7v-3.6h-10.6v7.1h3.6zm7 3.6v-3.6h-7v3.6h7zm3.6 0h-3.5v3.6h-3.6v3.5h3.6v3.6h3.6v-3.6h3.5v3.6h7.1v-3.6H328v-3.6h3.5v-3.5H328V246h-3.6v-3.6h-3.6v10.7zm0 0h3.6v3.6h-3.6v-3.6zm10.7-14.3v3.6H328v-3.6h3.5zm0-10.7v-10.6h-10.6v10.7h10.6zm-49.8 7.2H278v3.5h7.1v3.6H278v7.1h3.6v-3.5h3.5v3.5h3.6V239H285v-3.5h-3.5zm42.7-10.7h3.6V221h-3.6v3.6zm-35.6-3.6H285v3.6h3.6V221zm3.6-3.5h-10.7v10.7h10.6v-10.7zm-7.2 46.3h3.6v-3.6H285v3.6zm-7.1-10.7h17.8V271H278v-17.8zm3.6 14.2h10.6v-10.6h-10.6v10.6z"
        clipRule="evenodd"
      />
      <Path
        fill={color}
        d="M450.4 321a2.5 2.5 0 105 0h-5zm-51.3-79l25 14.4v-28.8L399 242zm56.3 79c0-12.5.2-23.8 0-33.6-.3-9.8-1-18.4-3-25.4-2.1-7.1-5.5-12.9-11-16.8-5.6-3.8-13-5.7-22.8-5.7v5a34 34 0 0119.9 4.8c4.3 3.1 7.2 7.7 9 14a101 101 0 012.9 24.3c.2 9.7 0 20.8 0 33.4h5z"
      />
      <Defs>
        <ClipPath id="a">
          <Path
            fill="#fff"
            d="M0 0h147v147H0z"
            transform="translate(391 333)"
          />
        </ClipPath>
      </Defs>
    </Svg>
  );
};
```

Does it solve the problem?

**Comment by StefanWallin** [comment]
Interesting! Thanks... I wonder why Figma outputted that. I'm no SVG expert. So not sure who's "In the wrong"...

**Comment by bohdanprog** [comment]
I'm going to try to look dipper into that issue, and if I find any others solutions I'll let you know ;)

**Comment by StefanWallin** [comment]
> @StefanWallin I'm not sure about the problem because when I changed that line: `<G mask="url(#a)">` to `<G>`
> Does it solve the problem? Or maybe I missed something.
This did solve the problem for me, but not quite sure what way it's "supposed" to be.

**Comment by bohdanprog** [comment]
> > @StefanWallin I'm not sure about the problem because when I changed that line: `<G mask="url(#a)">` to `<G>`
> > Does it solve the problem? Or maybe I missed something.
> 
> This did solve the problem for me, but not quite sure what way it's "supposed" to be.

Let's keep it open, and maybe folks can send some examples of how we can reproduce that issue.

**Comment by yousefArb** [comment]
Mask is not working when you put values as number or string for width, height, x and y inside the mask or its children or inside the children of the G with mask prop.
it's working for me when I use percentage only, or when I remove them.
@bohdanprog

**Comment by bohdanprog** [comment]
@yousefArb
It already merged [PR](https://github.com/software-mansion/react-native-svg/pull/2457) and should solve the problem.

**Comment by djaffer** [comment]
linearGradient doesn't work on web unless you refresh.

**Comment by MuneebQureshi1** [comment]
Hi Dev,

I was previously using version 15.6.0 in my React Native CLI project, but I encountered issues with some SVGs not rendering properly on iOS, although they worked fine on Android. I then upgraded to version 15.7.1, but the problem persisted.

After checking in Expo, I found that the SVGs were rendering correctly there. Upon examining the version that Expo is using, I discovered it was 15.2.0. After downgrading to that version, my SVGs started working fine again.

It seems there might be a regression or compatibility issue in versions 15.6.0 and 15.7.1 affecting iOS rendering when using SvgXml.

Thanks for looking into this!

**Comment by bohdanprog** [comment]
Hi @MuneebQureshi1,
Can you provide an example of your svg? It can help us to find the problem.
Thank you.

**Comment by MuneebQureshi1** [comment]
Here is my example svg.
<svg width="23" height="22" viewBox="0 0 23 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0_1189_3236" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="2" y="9" width="18" height="13">
<path d="M2.6875 9.24609H19.3615V21.2501H2.6875V9.24609Z" fill="white"/>
</mask>
<g mask="url(#mask0_1189_3236)">
<path d="M18.1154 19.7112C18.1154 19.9939 17.8862 20.2192 17.6087 20.2192H14.0537C13.7724 20.2192 13.5483 19.9887 13.5483 19.7112V14.4172C13.5483 13.5731 12.8657 12.8892 12.0255 12.8892H9.99206C9.15185 12.8892 8.46925 13.5731 8.46925 14.4172V19.7112C8.46925 19.9939 8.24129 20.2192 7.96382 20.2192H4.39585C4.11317 20.2192 3.88912 19.9887 3.88912 19.7112V9.50879H2.87305V19.7112C2.87305 20.554 3.55434 21.2392 4.39585 21.2392H7.9508C8.79101 21.2392 9.4736 20.554 9.4736 19.7112V14.4172C9.4736 14.1345 9.70157 13.9092 9.97903 13.9092H12.0125C12.2939 13.9092 12.5179 14.1397 12.5179 14.4172V19.7112C12.5179 20.554 13.2005 21.2392 14.0407 21.2392H17.5957C18.4359 21.2392 19.1185 20.554 19.1185 19.7112V9.50879H18.1024L18.1154 19.7112Z" fill="#BF6212"/>
</g>
<mask id="mask1_1189_3236" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="0" y="0" width="23" height="10">
<path d="M0 0H22.0005V9.91321H0V0Z" fill="white"/>
</mask>
<g mask="url(#mask1_1189_3236)">
<path d="M11.9909 0.504069C11.4139 0.0103626 10.5828 0.0103626 10.0057 0.504069L0 9.11983L0.660446 9.89361L10.67 1.27785C10.8641 1.11501 11.1416 1.11501 11.3305 1.27785L21.3414 9.89361L22.0005 9.11983L11.9909 0.504069Z" fill="#BF6212"/>
</g>
</svg>

**Comment by bohdanprog** [comment]
> @bohdanprog Here is my example svg.
> 
> ```
> <svg width="23" height="22" viewBox="0 0 23 22" fill="none" xmlns="http://www.w3.org/2000/svg">
> <mask id="mask0_1189_3236" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="2" y="9" width="18" height="13">
> <path d="M2.6875 9.24609H19.3615V21.2501H2.6875V9.24609Z" fill="white"/>
> </mask>
> <g mask="url(#mask0_1189_3236)">
> <path d="M18.1154 19.7112C18.1154 19.9939 17.8862 20.2192 17.6087 20.2192H14.0537C13.7724 20.2192 13.5483 19.9887 13.5483 19.7112V14.4172C13.5483 13.5731 12.8657 12.8892 12.0255 12.8892H9.99206C9.15185 12.8892 8.46925 13.5731 8.46925 14.4172V19.7112C8.46925 19.9939 8.24129 20.2192 7.96382 20.2192H4.39585C4.11317 20.2192 3.88912 19.9887 3.88912 19.7112V9.50879H2.87305V19.7112C2.87305 20.554 3.55434 21.2392 4.39585 21.2392H7.9508C8.79101 21.2392 9.4736 20.554 9.4736 19.7112V14.4172C9.4736 14.1345 9.70157 13.9092 9.97903 13.9092H12.0125C12.2939 13.9092 12.5179 14.1397 12.5179 14.4172V19.7112C12.5179 20.554 13.2005 21.2392 14.0407 21.2392H17.5957C18.4359 21.2392 19.1185 20.554 19.1185 19.7112V9.50879H18.1024L18.1154 19.7112Z" fill="#BF6212"/>
> </g>
> <mask id="mask1_1189_3236" style="mask-type:luminance" maskUnits="userSpaceOnUse" x="0" y="0" width="23" height="10">
> <path d="M0 0H22.0005V9.91321H0V0Z" fill="white"/>
> </mask>
> <g mask="url(#mask1_1189_3236)">
> <path d="M11.9909 0.504069C11.4139 0.0103626 10.5828 0.0103626 10.0057 0.504069L0 9.11983L0.660446 9.89361L10.67 1.27785C10.8641 1.11501 11.1416 1.11501 11.3305 1.27785L21.3414 9.89361L22.0005 9.11983L11.9909 0.504069Z" fill="#BF6212"/>
> </g>
> </svg>
> ```

I guess that issue should be resolved, here is how it looks in iOS:
<img src="https://github.com/user-attachments/assets/d8fdb620-3b90-4f7c-897e-cee151068104" width="350" height="700" />

**Comment by yousefArb** [comment]
@bohdanprog please, can you confirm this svg rendered properly with your fix ?
it should be like this 
![Screenshot 2024-10-01 at 9 28 40 AM](https://github.com/user-attachments/assets/cc73729d-7c87-4767-a50f-c91a16363e30)
but I got this 
![Screenshot 2024-10-01 at 9 30 50 AM](https://github.com/user-attachments/assets/0be689d9-f7be-460c-85c8-529b279f67f9)

the problem is with this tag 👇
```
<g filter="url(#filter0_d_272_19623)">
<path d="M85.8874 15.0156C83.9295 15.1394 82.094 15.9442 80.8091 17.306C80.6867 17.4298 80.5643 17.5536 80.442 17.7393C79.2794 19.1012 78.4229 20.8963 78.4229 22.8153V80.6317C78.4229 86.0172 74.1399 90.3503 68.8168 90.3503H22.0713V22.382C22.1937 20.4011 22.9279 18.6059 24.2128 17.306C25.62 15.8823 27.5168 15.0156 29.6583 15.0156H76.7097H85.6427C85.7039 15.0156 85.7651 15.0156 85.8874 15.0156Z" fill="url(#paint0_linear_272_19623)"/>
</g>
```
this is the svg code 👇
```
<svg width="121" height="124" viewBox="0 0 121 124" fill="none" xmlns="http://www.w3.org/2000/svg">
<ellipse cx="58.5" cy="51" rx="47.5" ry="48" fill="#EAEEF9"/>
<path d="M112.236 31.0882C114.491 31.0882 116.319 29.2443 116.319 26.9699C116.319 24.6954 114.491 22.8516 112.236 22.8516C109.981 22.8516 108.152 24.6954 108.152 26.9699C108.152 29.2443 109.981 31.0882 112.236 31.0882Z" fill="#EAEEF9"/>
<path d="M118.211 15.0156C119.751 15.0156 120.999 13.7564 120.999 12.2031C120.999 10.6498 119.751 9.39062 118.211 9.39062C116.67 9.39062 115.422 10.6498 115.422 12.2031C115.422 13.7564 116.67 15.0156 118.211 15.0156Z" fill="#EAEEF9"/>
<path d="M16.6731 10.4464C19.5334 10.4464 21.8521 8.10791 21.8521 5.22321C21.8521 2.33851 19.5334 0 16.6731 0C13.8129 0 11.4941 2.33851 11.4941 5.22321C11.4941 8.10791 13.8129 10.4464 16.6731 10.4464Z" fill="#EAEEF9"/>
<path d="M77.0764 24.7342H51.6846V15.0156H84.9693C85.0305 15.0156 85.0917 15.0156 85.1529 15.0156C90.3536 15.1394 94.5754 19.4726 94.5754 24.7342H83.5621" fill="#CCD4E2"/>
<g filter="url(#filter0_d_272_19623)">
<path d="M85.8874 15.0156C83.9295 15.1394 82.094 15.9442 80.8091 17.306C80.6867 17.4298 80.5643 17.5536 80.442 17.7393C79.2794 19.1012 78.4229 20.8963 78.4229 22.8153V80.6317C78.4229 86.0172 74.1399 90.3503 68.8168 90.3503H22.0713V22.382C22.1937 20.4011 22.9279 18.6059 24.2128 17.306C25.62 15.8823 27.5168 15.0156 29.6583 15.0156H76.7097H85.6427C85.7039 15.0156 85.7651 15.0156 85.8874 15.0156Z" fill="url(#paint0_linear_272_19623)"/>
</g>
<path d="M69.1213 28.2633H55.2322C54.7427 28.2633 54.3145 27.83 54.3145 27.3348C54.3145 26.8396 54.7427 26.4062 55.2322 26.4062H69.1213C69.6108 26.4062 70.0391 26.8396 70.0391 27.3348C70.0391 27.83 69.6719 28.2633 69.1213 28.2633Z" fill="#B3BFD3"/>
<path d="M48.6868 28.2633H30.576C30.0865 28.2633 29.6582 27.83 29.6582 27.3348C29.6582 26.8396 30.0865 26.4062 30.576 26.4062H48.748C49.2375 26.4062 49.6658 26.8396 49.6658 27.3348C49.6658 27.83 49.2375 28.2633 48.6868 28.2633Z" fill="#B3BFD3"/>
<path d="M60.3112 37.4235H42.2615C41.772 37.4235 41.3438 36.9902 41.3438 36.4949C41.3438 35.9997 41.772 35.5664 42.2615 35.5664H60.3112C60.8006 35.5664 61.2289 35.9997 61.2289 36.4949C61.2901 36.9902 60.8618 37.4235 60.3112 37.4235Z" fill="#B3BFD3"/>
<path d="M36.4498 37.4235H30.576C30.0865 37.4235 29.6582 36.9902 29.6582 36.4949C29.6582 35.9997 30.0865 35.5664 30.576 35.5664H36.4498C36.9392 35.5664 37.3675 35.9997 37.3675 36.4949C37.3675 36.9902 36.9392 37.4235 36.4498 37.4235Z" fill="#D4DBEC"/>
<path d="M69.1222 46.5875H58.0477C57.5582 46.5875 57.1299 46.1542 57.1299 45.659C57.1299 45.1638 57.5582 44.7305 58.0477 44.7305H69.1222C69.6117 44.7305 70.04 45.1638 70.04 45.659C70.04 46.1542 69.6729 46.5875 69.1222 46.5875Z" fill="#D4DBEC"/>
<path d="M52.725 46.5875H30.576C30.0865 46.5875 29.6582 46.1542 29.6582 45.659C29.6582 45.1638 30.0865 44.7305 30.576 44.7305H52.725C53.2145 44.7305 53.6428 45.1638 53.6428 45.659C53.6428 46.1542 53.2757 46.5875 52.725 46.5875Z" fill="#B3BFD3"/>
<path d="M60.3114 55.7477H48.1356C47.6461 55.7477 47.2178 55.3144 47.2178 54.8192C47.2178 54.3239 47.6461 53.8906 48.1356 53.8906H60.3114C60.8009 53.8906 61.2292 54.3239 61.2292 54.8192C61.2904 55.3144 60.8621 55.7477 60.3114 55.7477Z" fill="#B3BFD3"/>
<path d="M42.813 55.7477H30.576C30.0865 55.7477 29.6582 55.3144 29.6582 54.8192C29.6582 54.3239 30.0865 53.8906 30.576 53.8906H42.8742C43.3637 53.8906 43.792 54.3239 43.792 54.8192C43.792 55.3144 43.3637 55.7477 42.813 55.7477Z" fill="#D4DBEC"/>
<path d="M69.1217 64.9078H60.617C60.1275 64.9078 59.6992 64.4745 59.6992 63.9793C59.6992 63.4841 60.1275 63.0508 60.617 63.0508H69.1217C69.6112 63.0508 70.0395 63.4841 70.0395 63.9793C70.0395 64.4745 69.6724 64.9078 69.1217 64.9078Z" fill="#B3BFD3"/>
<path d="M55.1114 64.9078H40.8553C40.3658 64.9078 39.9375 64.4745 39.9375 63.9793C39.9375 63.4841 40.3658 63.0508 40.8553 63.0508H55.1114C55.6009 63.0508 56.0292 63.4841 56.0292 63.9793C56.0292 64.4745 55.6009 64.9078 55.1114 64.9078Z" fill="#D4DBEC"/>
<path d="M35.532 64.9078H30.576C30.0865 64.9078 29.6582 64.4745 29.6582 63.9793C29.6582 63.4841 30.0865 63.0508 30.576 63.0508H35.532C36.0215 63.0508 36.4498 63.4841 36.4498 63.9793C36.4498 64.4745 36.0215 64.9078 35.532 64.9078Z" fill="#B3BFD3"/>
<path d="M60.3115 74.0719H51.868C51.3785 74.0719 50.9502 73.6386 50.9502 73.1434C50.9502 72.6482 51.3785 72.2148 51.868 72.2148H60.3115C60.801 72.2148 61.2293 72.6482 61.2293 73.1434C61.2905 73.6386 60.8622 74.0719 60.3115 74.0719Z" fill="#B3BFD3"/>
<path d="M46.3006 74.0719H30.576C30.0865 74.0719 29.6582 73.6386 29.6582 73.1434C29.6582 72.6482 30.0865 72.2148 30.576 72.2148H46.3006C46.7901 72.2148 47.2184 72.6482 47.2184 73.1434C47.2184 73.6386 46.7901 74.0719 46.3006 74.0719Z" fill="#D4DBEC"/>
<path d="M48.2579 82.6758H60.6173C60.6173 84.7805 61.4739 86.6994 62.82 88.0613C64.1661 89.485 66.0628 90.2897 68.1431 90.2897H12.5258C10.4455 90.2897 8.54874 89.4231 7.20267 88.0613C5.85659 86.6994 5 84.7805 5 82.6758H41.5887C41.5887 82.6758 48.3803 82.7377 48.2579 82.6758Z" fill="#CCD4E2"/>
<path d="M101.318 76.747L93.5928 68.9619L95.3638 67.1758L103.083 74.967L101.318 76.747Z" fill="#858B9B"/>
<path d="M104.004 79.4835L98.08 73.5092C97.5853 73.0103 97.5853 72.1973 98.08 71.6984C98.5746 71.1995 99.3808 71.1995 99.8754 71.6984L105.799 77.6727C106.294 78.1716 106.294 78.9846 105.799 79.4835C105.305 79.9824 104.498 79.9824 104.004 79.4835Z" fill="#858B9B"/>
<path d="M103.582 79.8678L95.961 72.1813C95.7838 72.0027 95.7838 71.7132 95.961 71.5284L97.9091 69.5636C98.0862 69.385 98.3732 69.385 98.5564 69.5636L106.178 77.2502C106.355 77.4288 106.355 77.7183 106.178 77.9031L104.23 79.8678C104.047 80.0464 103.76 80.0464 103.582 79.8678Z" fill="url(#paint1_linear_272_19623)"/>
<path d="M84.8474 43.875C76.7617 43.875 70.209 50.4837 70.209 58.6384C70.209 66.7869 76.7617 73.4017 84.8413 73.4017C92.9269 73.4017 99.4796 66.793 99.4796 58.6384C99.4796 50.4837 92.9269 43.875 84.8474 43.875ZM84.8474 70.6671C78.3557 70.6671 73.0976 65.2779 73.0976 58.6322C73.0976 51.9865 78.3557 46.6035 84.8474 46.6035C91.3391 46.6035 96.5971 51.9927 96.5971 58.6384C96.5971 65.284 91.333 70.6671 84.8474 70.6671Z" fill="url(#paint2_linear_272_19623)"/>
<defs>
<filter id="filter0_d_272_19623" x="0.0712891" y="4.01562" width="107.816" height="119.336" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dy="11"/>
<feGaussianBlur stdDeviation="11"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.397708 0 0 0 0 0.47749 0 0 0 0 0.575 0 0 0 0.27 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_272_19623"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_272_19623" result="shape"/>
</filter>
<linearGradient id="paint0_linear_272_19623" x1="53.9586" y1="13.2731" x2="53.9586" y2="91.1625" gradientUnits="userSpaceOnUse">
<stop stop-color="#FDFEFF"/>
<stop offset="0.9964" stop-color="#ECF0F5"/>
</linearGradient>
<linearGradient id="paint1_linear_272_19623" x1="95.8233" y1="74.7169" x2="106.313" y2="74.7169" gradientUnits="userSpaceOnUse">
<stop stop-color="#B0BACC"/>
<stop offset="1" stop-color="#969EAE"/>
</linearGradient>
<linearGradient id="paint2_linear_272_19623" x1="70.1956" y1="58.6416" x2="99.485" y2="58.6416" gradientUnits="userSpaceOnUse">
<stop stop-color="#B0BACC"/>
<stop offset="1" stop-color="#969EAE"/>
</linearGradient>
</defs>
</svg>
```

**Comment by bohdanprog** [comment]
Hello @yousefArb,
I guess [here](https://github.com/software-mansion/react-native-svg/issues/2362) you can find the answer to your question.

**Comment by MuneebQureshi1** [comment]
> here

Which react native svg versions are you using?

**Comment by bohdanprog** [comment]
> [#2422 (comment)](https://github.com/software-mansion/react-native-svg/issues/2422#issuecomment-2384875347) @bohdanprog Which react native svg versions are you using?

I ran your example from the main branch. 
I believe we are going to release a new version soon.

**Comment by djaffer** [comment]
The problem is still there. I have to get 2 copies of the same image with different names. It doesn't load in a different route page when using react native navigations.

**Comment by bohdanprog** [comment]
@djaffer Can you provide a repro of how we can reproduce that problem?
